Repository CMPT276-Project-Group-6/Realtorest, pull requests merged in 2024-04, with the labels that each got.

#139 Refactor: Auto Formatting to make syntax more consistent
  src/main/java/cmpt276/pg6/realtorest/controllers/MainController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/PropertyController.java
  src/main/java/cmpt276/pg6/realtorest/models/PropertyRepository.java
  src/main/java/cmpt276/pg6/realtorest/models/User.java
  src/main/resources/static/css/dev.css
  src/main/resources/static/css/filterBar.css
  src/main/resources/static/css/login.css
  src/main/resources/static/css/propertyListing.css
  src/main/resources/static/css/register.css
  src/main/resources/static/js/propertyListing.js
  src/main/resources/templates/dev/properties.html
  src/main/resources/templates/propertyListing.html
  src/main/resources/templates/users/adminlogin.html
  src/main/resources/templates/users/login.html
  src/main/resources/templates/users/register.html
Labels: enhancement

#149 Implementing functionality to send mails using Mailgun API
  .gitignore
  pom.xml
  src/main/java/cmpt276/pg6/realtorest/RealtorestApplication.java
  src/main/java/cmpt276/pg6/realtorest/controllers/MailgunController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/MainController.java
  src/main/resources/templates/dev/mail.html
Labels: enhancement, api

#158 Refactor: Extracting stuff from the main controller and some other stuff
  src/main/java/cmpt276/pg6/realtorest/controllers/AdminController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/MailgunController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/MainController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/PropertyController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/RedirectController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/UserController.java
  src/test/java/cmpt276/pg6/realtorest/controllers/ControllersTest.java
Labels: enhancement

#159 Implementing mailing list to send out emails to a list of addresses
  src/main/java/cmpt276/pg6/realtorest/controllers/MailgunController.java
  src/main/resources/templates/dev/mail.html
  src/test/java/cmpt276/pg6/realtorest/controllers/ControllersTests.java
Labels: feature, api

#161 Mailing list functionality is all here now
  src/main/java/cmpt276/pg6/realtorest/controllers/MailgunController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/UserController.java
  src/main/java/cmpt276/pg6/realtorest/models/User.java
  src/main/java/cmpt276/pg6/realtorest/models/UserRepository.java
  src/main/resources/templates/dev/users.html
Labels: feature, database, api

#169 Various stuff Kevin was working on today
  src/main/java/cmpt276/pg6/realtorest/controllers/AdminController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/FavouriteController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/MailgunController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/MainController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/PropertyController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/RedirectController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/UserController.java
  src/main/resources/templates/dev/edit-property.html
  src/main/resources/templates/dev/properties.html
  src/test/java/cmpt276/pg6/realtorest/controllers/ControllersTests.java
Labels: enhancement

#174 Fixed clicking "back" after logging in still shows the login page
  src/main/java/cmpt276/pg6/realtorest/controllers/UserController.java
Labels: bug

#175 Logout navigation
  src/main/java/cmpt276/pg6/realtorest/controllers/FavouriteController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/UserController.java
Labels: bug

#179 Fixed show Favourites page test
  src/test/java/cmpt276/pg6/realtorest/controllers/ControllersTests.java
Labels: bug

#181 Fixed duplicated closing tag
  src/main/resources/static/css/login.css
  src/main/resources/templates/user/login.html
Labels: bug, ui

#185 Created UI for user settings page
  src/main/java/cmpt276/pg6/realtorest/controllers/UserController.java
  src/main/java/cmpt276/pg6/realtorest/models/PropertyRepository.java
  src/main/java/cmpt276/pg6/realtorest/models/User.java
  src/main/resources/static/css/propertyListing.css
  src/main/resources/static/css/settings.css
  src/main/resources/static/img/settingsBackground.jpg
  src/main/resources/static/js/greeting.js
  src/main/resources/templates/dev/users.html
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/user/settings.html
Labels: ui

#189 Removed duplicated property listings page
  src/main/java/cmpt276/pg6/realtorest/controllers/FavouriteController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/MailgunController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/PropertyController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/UserController.java
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/home.html
  src/main/resources/templates/user/settings.html
  src/test/java/cmpt276/pg6/realtorest/controllers/ControllersTests.java
Labels: enhancement

#190 Change mailing list to use first and last name of users instead
  src/main/java/cmpt276/pg6/realtorest/controllers/MailgunController.java
  src/main/resources/static/css/homepage.css
  src/main/resources/static/css/settings.css
  src/main/resources/static/js/greeting.js
Labels: feature, api

#191 Disabling password confirmation field to make user settings page work
  src/main/resources/templates/user/settings.html
Labels: bug

#192 Fixed the issues with password checks
  src/main/resources/templates/user/settings.html
Labels: bug

#195 Pages can now display images from the database
  src/main/java/cmpt276/pg6/realtorest/controllers/FavouriteController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/ImageController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/MainController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/PropertyController.java
  src/main/resources/static/img/Property1/Front.jpg
  src/main/resources/static/img/Property1/Livingroom.jpeg
  src/main/resources/static/img/Property1/Washroom.jpg
  src/main/resources/static/js/propertyListing.js
  src/main/resources/templates/favourites.html
  src/main/resources/templates/home.html
  src/main/resources/templates/propertyListing.html
Labels: feature, ui, database

#197 Added mortgage calculator
  src/main/java/cmpt276/pg6/realtorest/controllers/MainController.java
  src/main/resources/static/css/mortgage.css
  src/main/resources/static/img/mortgagecalcbackground.jpg
  src/main/resources/static/js/mortgage-calculator.js
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/mortgage-calculator.html
Labels: feature

#216 Added grabbing user session to property listings page
  src/main/java/cmpt276/pg6/realtorest/controllers/MainController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/PropertyController.java
Labels: bug, ui

#228 Added submission documents and modified Readme
  Documentation/Submission/Requirements and Specification Document.pdf
  Documentation/Submission/Submission.txt
  README.md
Labels: documentation

#231 Fixed issue where visiting a page with incorrect account type causes issues
  src/main/java/cmpt276/pg6/realtorest/controllers/AdminController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/BaseController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/FavoriteController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/ImageController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/MailgunController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/MainController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/PropertyController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/RedirectController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/UserController.java
  src/main/resources/templates/fragments/navbar-admin.html
  src/main/resources/templates/fragments/navbar.html
  src/test/java/cmpt276/pg6/realtorest/controllers/ControllersTests.java
Labels: bug

#240 Using a filter to disable cache for all pages
  src/main/java/cmpt276/pg6/realtorest/NoCacheFilter.java
  src/main/java/cmpt276/pg6/realtorest/WebConfig.java
  src/main/java/cmpt276/pg6/realtorest/controllers/FavoriteController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/UserController.java
Labels: bug

#243 Added tests for admin login functionalities
  src/test/java/cmpt276/pg6/realtorest/RealtorestApplicationTests.java
  src/test/java/cmpt276/pg6/realtorest/controllers/AdminControllerTests.java
  src/test/java/cmpt276/pg6/realtorest/controllers/ControllersTests.java
Labels: enhancement

#246 Updated submission document
  Documentation/Submission/Requirements and Specification Document.pdf
Labels: documentation

#251 Added tests for password reset feature
  src/main/java/cmpt276/pg6/realtorest/controllers/MailgunController.java
  src/test/java/cmpt276/pg6/realtorest/controllers/ControllersTests.java
Labels: enhancement

#252 Added more tests for the property controller
  src/main/java/cmpt276/pg6/realtorest/models/PropertyRepository.java
  src/test/java/cmpt276/pg6/realtorest/controllers/PropertyControllerTest.java
Labels: enhancement

#255 Fixed dropdown visual bug that only occurs on some operating systems
  src/main/resources/static/css/admin-edit-listings.css
  src/main/resources/static/css/admin-property-listings.css
  src/main/resources/static/css/mortgage.css
  src/main/resources/templates/property-listings.html
Labels: bug, ui

#254 Refactor: Autoformatting, changed test names to be more consistent, and removed some signed comments
  src/main/java/cmpt276/pg6/realtorest/controllers/AdminController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/FavoriteController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/ImageController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/MailgunController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/MainController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/PropertyController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/RedirectController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/UserController.java
  src/main/java/cmpt276/pg6/realtorest/models/User.java
  src/test/java/cmpt276/pg6/realtorest/controllers/ControllersTests.java
  src/test/java/cmpt276/pg6/realtorest/controllers/PropertyControllerTest.java
  src/test/java/cmpt276/pg6/realtorest/controllers/PropertyControllerTests.java
Labels: enhancement

#256 Updated submission file to version 3
  Documentation/Submission/Requirements and Specification Document.pdf
Labels: documentation

#257 Updated submission file to version 4
  Documentation/Submission/Requirements and Specification Document.pdf
Labels: documentation

#267 Some final updates to documentation
  Documentation/Submission/Submission.txt
  README.md
Labels: documentation
