Repository CMPT276-Project-Group-6/Realtorest, pull requests merged in 2024-03, with the labels that each got.

#13 Doing a pull request practice for Kevin
  .gitignore
  .vscode/settings.json
  Documentation/GitHub/PullRequestPractice.md
Labels: documentation

#19 Practice pull request for Amrit
  Documentation/GitHub/PullRequestPractice.md
Labels: documentation

#21 Practice pull request for Malaika
  Documentation/GitHub/PullRequestPractice.md
Labels: documentation

#23 Cleanup the practice pull requests and to get things done
  Documentation/GitHub/PullRequestPractice.md
  src/main/resources/static/ProjectInitialized.html
Labels: documentation

#27 Deploying project onto Render.com
  Dockerfile
Labels: enhancement

#29 Setting up database, Model View Controller, and added some examples from Bobby
  .gitignore
  pom.xml
  src/main/java/cmpt276/pg6/realtorest/RealtorestApplication.java
  src/main/java/cmpt276/pg6/realtorest/controllers/ExampleUsersController.java
  src/main/java/cmpt276/pg6/realtorest/controllers/HomeController.java
  src/main/java/cmpt276/pg6/realtorest/models/ExampleUser.java
  src/main/java/cmpt276/pg6/realtorest/models/ExampleUserRepository.java
  src/main/resources/application.properties
  src/main/resources/static/exampleAddUser.html
  src/main/resources/templates/exampleUsers/exampleAddedUser.html
  src/main/resources/templates/exampleUsers/exampleLogin.html
  src/main/resources/templates/exampleUsers/exampleProtected.html
  src/main/resources/templates/exampleUsers/exampleShowAll.html
  src/main/resources/templates/main.html
Labels: enhancement, database

#38 Creating the first version of the listing page
  src/main/java/cmpt276/pg6/realtorest/controllers/HomeController.java
  src/main/resources/static/CSS/Montserrat/Montserrat-Italic-VariableFont_wght.ttf
  src/main/resources/static/CSS/Montserrat/Montserrat-VariableFont_wght.ttf
  src/main/resources/static/CSS/Montserrat/OFL.txt
  src/main/resources/static/CSS/Montserrat/README.txt
  src/main/resources/static/CSS/Montserrat/static/Montserrat-Black.ttf
  src/main/resources/static/CSS/Montserrat/static/Montserrat-BlackItalic.ttf
  src/main/resources/static/CSS/Montserrat/static/Montserrat-Bold.ttf
  src/main/resources/static/CSS/Montserrat/static/Montserrat-BoldItalic.ttf
  src/main/resources/static/CSS/Montserrat/static/Montserrat-ExtraBold.ttf
  src/main/resources/static/CSS/Montserrat/static/Montserrat-ExtraBoldItalic.ttf
  src/main/resources/static/CSS/Montserrat/static/Montserrat-ExtraLight.ttf
  src/main/resources/static/CSS/Montserrat/static/Montserrat-ExtraLightItalic.ttf
  src/main/resources/static/CSS/Montserrat/static/Montserrat-Italic.ttf
  src/main/resources/static/CSS/Montserrat/static/Montserrat-Light.ttf
  src/main/resources/static/CSS/Montserrat/static/Montserrat-LightItalic.ttf
  src/main/resources/static/CSS/Montserrat/static/Montserrat-Medium.ttf
  src/main/resources/static/CSS/Montserrat/static/Montserrat-MediumItalic.ttf
  src/main/resources/static/CSS/Montserrat/static/Montserrat-Regular.ttf
  src/main/resources/static/CSS/Montserrat/static/Montserrat-SemiBold.ttf
  src/main/resources/static/CSS/Montserrat/static/Montserrat-SemiBoldItalic.ttf
  src/main/resources/static/CSS/Montserrat/static/Montserrat-Thin.ttf
  src/main/resources/static/CSS/Montserrat/static/Montserrat-ThinItalic.ttf
  src/main/resources/static/CSS/Property1/Front.jpg
  src/main/resources/static/CSS/Property1/Livingroom.jpeg
  src/main/resources/static/CSS/Property1/Washroom.jpg
  src/main/resources/static/CSS/Property2/Front.jpg
  src/main/resources/static/CSS/Property2/Livingroom.jpg
  src/main/resources/static/CSS/Property2/Washroom.jpg
  src/main/resources/static/CSS/Property3/Front.jpg
  src/main/resources/static/CSS/Property3/Livingroom.jpeg
  src/main/resources/static/CSS/Property3/Washroom.jpg
  src/main/resources/static/CSS/Property4/Front.jpg
  src/main/resources/static/CSS/Property4/Livingroom.jpg
  src/main/resources/static/CSS/Property4/Washroom.jpg
  src/main/resources/static/CSS/Property5/Front.jpg
  src/main/resources/static/CSS/Property5/Livingroom.jpeg
  src/main/resources/static/CSS/Property5/Washroom.jpg
  src/main/resources/static/CSS/Property6/Front.jpg
  src/main/resources/static/CSS/Property6/Livingroom.jpg
  src/main/resources/static/CSS/Property6/Washroom.jpg
  src/main/resources/static/CSS/PropertyListing.css
  src/main/resources/static/CSS/profile.jpg
  src/main/resources/static/CSS/wallpaper.jpg
  src/main/resources/static/JS/PropertyListing.js
  src/main/resources/templates/PropertyListing.html
Labels: feature, ui

#47 Linked Home and Listing Page
  src/main/java/cmpt276/pg6/realtorest/controllers/HomeController.java
  src/main/resources/static/css/homepage.css
  src/main/resources/static/css/profile.jpg
  src/main/resources/static/css/propertyListing.css
  src/main/resources/static/css/register.css
  src/main/resources/static/img/homepage/wallpaper.webp
  src/main/resources/static/img/homepage/wallpaper2.jpg
  src/main/resources/static/js/propertyListing.js
  src/main/resources/templates/PropertyListing.html
  src/main/resources/templates/home.html
  src/main/resources/templates/propertyListing.html
  src/main/resources/templates/users/listAll.html
  src/main/resources/templates/users/login.html
  src/main/resources/templates/users/protected.html
  src/main/resources/templates/users/register.html
Labels: feature, ui

#54 Login-Logout
  src/main/java/cmpt276/pg6/realtorest/controllers/UserController.java
  src/main/resources/templates/home.html
  src/main/resources/templates/propertyListing.html
  src/main/resources/templates/users/login.html
  src/main/resources/templates/users/protected.html
Labels: feature, ui

#58 Fixed database issue where "username" and "name" are being used inconsistently
  src/main/java/cmpt276/pg6/realtorest/controllers/MainController.java
  src/main/java/cmpt276/pg6/realtorest/models/User.java
  src/main/resources/templates/dev/admin.html
  src/main/resources/templates/dev/protected.html
  src/main/resources/templates/users/register.html
Labels: bug, ui, database

#59 Improved aesthetics of login page UI
  src/main/resources/static/css/login.css
  src/main/resources/templates/users/login.html
Labels: ui

#67 Refactor: Removed all DS_Store files
  .DS_Store
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/cmpt276/.DS_Store
  src/main/java/cmpt276/pg6/.DS_Store
  src/main/java/cmpt276/pg6/realtorest/.DS_Store
Labels: enhancement

#83 Created properties database for storing property listings, and added dev page to manage it
  src/main/java/cmpt276/pg6/realtorest/RealtorestApplication.java
  src/main/java/cmpt276/pg6/realtorest/controllers/MainController.java
  src/main/java/cmpt276/pg6/realtorest/models/Property.java
  src/main/java/cmpt276/pg6/realtorest/models/PropertyRepository.java
  src/main/java/cmpt276/pg6/realtorest/models/User.java
  src/main/java/cmpt276/pg6/realtorest/models/UserRepository.java
  src/main/resources/templates/dev/properties.html
  src/main/resources/templates/dev/users.html
Labels: enhancement, database

#85 Setting up the basics of unit tests
  src/main/java/cmpt276/pg6/realtorest/controllers/MainController.java
  src/test/java/cmpt276/pg6/realtorest/RealtorestApplicationTests.java
  src/test/java/cmpt276/pg6/realtorest/controllers/MainControllerTest.java
Labels: enhancement

#90 Added some useful stuff to the dev pages
  src/main/java/cmpt276/pg6/realtorest/controllers/MainController.java
  src/main/resources/templates/dev/properties.html
  src/main/resources/templates/dev/users.html
Labels: enhancement, database

#91 Refactor: Autoformatted every Java file and auto organized imports
  src/main/java/cmpt276/pg6/realtorest/controllers/MainController.java
  src/main/java/cmpt276/pg6/realtorest/models/UserRepository.java
  src/test/java/cmpt276/pg6/realtorest/RealtorestApplicationTests.java
  src/test/java/cmpt276/pg6/realtorest/controllers/MainControllerTest.java
Labels: enhancement

#86 Implementing some more unit tests
  src/test/java/cmpt276/pg6/realtorest/controllers/MainControllerTest.java
Labels: enhancement

#93 Refactor: Some minor auto formatting and moved images to img folder
  src/main/java/cmpt276/pg6/realtorest/controllers/MainController.java
  src/main/resources/static/css/login.css
  src/main/resources/static/css/propertyListing.css
  src/main/resources/static/css/register.css
  src/main/resources/static/img/Property1/Front.jpg
  src/main/resources/static/img/Property1/Livingroom.jpeg
  src/main/resources/static/img/Property1/Washroom.jpg
  src/main/resources/static/img/Property2/Front.jpg
  src/main/resources/static/img/Property2/Livingroom.jpg
  src/main/resources/static/img/Property2/Washroom.jpg
  src/main/resources/static/img/Property3/Front.jpg
  src/main/resources/static/img/Property3/Livingroom.jpeg
  src/main/resources/static/img/Property3/Washroom.jpg
  src/main/resources/static/img/Property4/Front.jpg
  src/main/resources/static/img/Property4/Livingroom.jpg
  src/main/resources/static/img/Property4/Washroom.jpg
  src/main/resources/static/img/Property5/Front.jpg
  src/main/resources/static/img/Property5/Livingroom.jpeg
  src/main/resources/static/img/Property5/Washroom.jpg
  src/main/resources/static/img/Property6/Front.jpg
  src/main/resources/static/img/Property6/Livingroom.jpg
  src/main/resources/static/img/Property6/Washroom.jpg
  src/main/resources/static/js/propertyListing.js
  src/main/resources/templates/propertyListing.html
Labels: enhancement

#104 Adding functionality to check strength of password when registering
  src/main/resources/static/css/register.css
  src/main/resources/templates/users/register.html
Labels: feature, ui

#105 Added some more advice for the person reviewing and marking the project
  Documentation/Screenshots/GitHub Projects - All Issues.png
  Documentation/Screenshots/GitHub Projects - All Pull Requests.png
  Documentation/Screenshots/GitHub Projects - Timeline.png
  README.md
  image.png
Labels: documentation

#106 Added functionality to indicate invalid credentials when logging in
  src/main/java/cmpt276/pg6/realtorest/controllers/MainController.java
  src/main/resources/templates/users/login.html
Labels: feature, ui

#107 Used MockBean for unit tests to prevent running test creates entry in database, and some other minor changes
  src/main/java/cmpt276/pg6/realtorest/controllers/MainController.java
  src/test/java/cmpt276/pg6/realtorest/controllers/MainControllerTest.java
Labels: enhancement

#111 Added popup after inactivity
  src/main/resources/static/css/propertyListing.css
  src/main/resources/static/js/propertyListing.js
  src/main/resources/templates/propertyListing.html
Labels: feature, ui

#114 Added some more unit tests
  src/main/java/cmpt276/pg6/realtorest/controllers/MainController.java
  src/test/java/cmpt276/pg6/realtorest/controllers/MainControllerTest.java
Labels: enhancement
